name: Lint with Pylint

on:
  pull_request:
    branches: [ main, "2.0" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.test.txt
        pip install --upgrade "homeassistant==2026.4.*"

    - name: Run pylint
      run: |
        source venv/bin/activate
        pylint custom_components/aux_cloud --fail-under=9.7
